### 1. Loading CSV file into pandas

In [2]:
import pandas as pd
csv_path = 'data.csv'
df = pd.read_csv(csv_path,encoding='utf-8')

### 2. Basic Data Exploration
- df.head()       ==>>             Loads first 5 Rows
- df.tail()       ==>>             Loads last 5 Rows
- df.shape        ==>>             Identify the size of Dataset
- df.columns      ==>>             Listing all column names
- df.info()       ==>>             range_indexes, non-null count, dtype of each column
- df.dtypes       ==>>             ''pandas.SERIES'' having data types of all columns

In [3]:
df.head()
# print(df.head())

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [5]:
x, y = df.shape
print(f'{csv_path} has:\n {x} rows \n {y} columns.')

data.csv has:
 1000 rows
 24 columns.

In [6]:
col_list = df.columns
print(f"{csv_path} columns are:")
print(*col_list,sep=",\t")

data.csv columns are:
product_id,	title,	product_description,	rating,	ratings_count,	initial_price,	discount,	final_price,	currency,	images,	delivery_options,	product_details,	breadcrumbs,	product_specifications,	amount_of_stars,	what_customers_said,	seller_name,	sizes,	videos,	seller_information,	variations,	best_offer,	more_offers,	category

In [7]:
df.info()
# print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [8]:
# Note: Type of any column will be a 'SERIES'
type(df['title'])

pandas.Series

In [9]:
# To check data type of column use 'dtype'
df['title'].dtype

In [10]:
# But you need to put in a PRINT()
print(df['title'].dtype)

str

In [11]:
# To check all dtypes ( No need to use PRINT() )
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

### Checking the Data for inconsistencies
(see Outcomes below)
- df.iloc[0]        ==>>        seeing the first row
- df,isna().sum()   ==>>        What columns have null values (Returns a **SERIES**)
- df.loc[df["seller_name"].notna(), "seller_name"]  ==>> see Not null values in that column.

In [12]:
df.iloc[0]

product_id                                                          8376765
title                                                           Lino Perros
product_description                          Women Navy Blue Solid Backpack
rating                                                                  3.8
ratings_count                                                            15
initial_price                                                          3995
discount                                                               58.0
final_price                                                     "₹3,995.00"
currency                                                                INR
images                    http://assets.myntassets.com/assets/images/837...
delivery_options          ["100% Original Products","Pay on delivery mig...
product_details           {"description":"Navy Blue solid backpackNon-Pa...
breadcrumbs               [{"name":"Accessories","url":"https://www.mynt...
product_specifications    [{"specification_name":"Add-Ons","specificatio...
amount_of_stars           {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...
what_customers_said                                                     NaN
seller_name                                                             NaN
sizes                                                  [{"size":"Onesize"}]
videos                                                ["rw-8376765_cae700"]
seller_information                                                      NaN
variations                                                             [{}]
best_offer                                                               {}
more_offers               [{"offer_name":"10% Instant Discount on Citi C...
category                                                          backpacks
Name: 0, dtype: object

In [13]:
# This query returns a ***SERIES***
# df.isna().sum()

# To print only those which are nonzero sum
df.isna().sum()[df.isna().sum()>0]

discount               121
what_customers_said    573
seller_name            301
videos                 781
seller_information     301
variations             562
dtype: int64

In [14]:
df.loc[df["seller_name"].notna(), "seller_name"]

5      H &███Hen███ & █████████eta█████████████████████
11                                       Sig███Ove███as
12                 Bel███Cas███ash█████████ail█████████
18                    Kas███r L███her█████████Pvt██████
19           PVH███VIN███ASH█████████TE ███████████████
                             ...
986             TIM███T R███IL █████████RIV████████████
991                   DES███ER ███GRE█████████IA ██████
992                                  Fla███ech███tai███
993                                      Br ███erp███es
998                                      Tru███m R███il
Name: seller_name, Length: 699, dtype: str

In [15]:
df.loc[df["seller_information"].notna(), "seller_information"]

5      Pra███yat███fra█████████PVT███████████████████...
11     Old███. 2███162█████████o. ███████████████████...
12     E-1███103███PIP█████████ IN███████████████████...
18      A-5███ADA███R V█████████ De█████████████████████
19     PVH███vin███ash█████████tdN███████████████████...
                             ...
986    Fla███o. ███, 6█████████y C███████████████████...
991    Fir███Flo███ Pl█████████, I███████████████████...
992    3rd███165███th █████████, s███████████████████...
993        Kha███ no███122█████████lhi██████████████████
998    Sho███o. ███-10█████████enu███████████████████...
Name: seller_information, Length: 699, dtype: str

In [16]:
df.loc[df["variations"].notna(), "variations"]

0                                             [{}]
1                                          [{},{}]
2                              [{},{},{},{},{},{}]
4      [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
5                                          [{},{}]
                          ...
982                            [{},{},{},{},{},{}]
983                            [{},{},{},{},{},{}]
989                                        [{},{}]
997                      [{},{},{},{},{},{},{},{}]
999                                  [{},{},{},{}]
Name: variations, Length: 438, dtype: str

In [17]:
df.loc[df["videos"].notna(), "videos"]

0                                  ["rw-8376765_cae700"]
1                                  ["rw-9136281_cae700"]
2      ["https://videos.myntassets.com/assets/videos/...
3      ["https://videos.myntassets.com/assets/videos/...
40                                ["rw-18100576_cae700"]
                             ...
991    ["https://videos.myntassets.com/assets/videos/...
992    ["https://videos.myntassets.com/assets/videos/...
994    ["rw-8481603_cae700","https://videos.myntasset...
995                                      ["pi-13698258"]
996    ["rw-16896006_cae700","https://videos.myntasse...
Name: videos, Length: 219, dtype: str

In [18]:
df.loc[df["best_offer"].notna(), "best_offer"]

0                                                     {}
1                                                     {}
2                                                     {}
3                                                     {}
4                                                     {}
                             ...
995                                                   {}
996                                                   {}
997                                                   {}
998    {"applicable_on":"Orders above Rs. 1499 (only ...
999                                                   {}
Name: best_offer, Length: 1000, dtype: str

### Outcomes
| Observation                                                      | Actions                   |
|------------------------------------------------------------------|---------------------------|
| 1. Currency column has every value == 'INR'.                     | Removing Currency column. |
| 2. Final Price is a string column.                               | Convert to Integer.       |
| 3. Discount values are NULL.                                     | Fill with zero.           |
| 4. Encodings are different for (seller_name,seller_information). | Remove column.            |
| 5. Variations column contain empty braces.                       | Remove column.            |
| 6. Videos have the most null values.                             | Remove column.            |
| 7. Best offer columns has {} for null values.                    | Replace with NULL.        |

In [19]:
# Drop these Columns
df_dropped= df.drop(['currency','seller_name','seller_information','variations','videos'],axis=1)


# fill discount Nan values with zero
df_dropped["discount"] = df_dropped["discount"].fillna(0).astype(float)

# Change Data type
df_dropped["final_price"] = (
    df_dropped["final_price"]
    .str.replace("₹", "", regex=False)
    .str.replace("\"", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

# Replace {} in best_offer column
df_dropped["best_offer"] = df_dropped["best_offer"].replace("{}", pd.NA)

### Intermediate Cleaned Dataset(df_dropped)

In [20]:
df_dropped.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,sizes,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,http://assets.myntassets.com/assets/images/837...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue solid backpackNon-Pa...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,"[{""size"":""Onesize""}]",NaN,"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,http://assets.myntassets.com/assets/images/913...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue backpackNon-Padded h...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,"[{""size"":""Onesize""}]",NaN,"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,http://assets.myntassets.com/assets/images/176...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,"[{""size"":""S""}]",NaN,"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,"[{""size"":""Onesize""}]",NaN,"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,http://assets.myntassets.com/assets/images/pro...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue solid bath robe, has a sh...","[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [21]:
df_dropped.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                1000 non-null   float64
 7   final_price             1000 non-null   float64
 8   images                  1000 non-null   str
 9   delivery_options        1000 non-null   str
 10  product_details         1000 non-null   str
 11  breadcrumbs             1000 non-null   str
 12  product_specifications  1000 non-null   str
 13  amount_of_stars         1000 non-null   str
 14  what_customers_said     427 non-null    str
 15  sizes                   1000 non-null   str
 16  best_offer              694 non-null    str
 17  more_offers             1000 non-null   str
 18  category                1000 non-null   str
dtypes: float64(3), int64(3), str(13)
memory usage: 148.6 KB

In [22]:
df_dropped.isna().sum()[df_dropped.isna().sum() > 0]

what_customers_said    573
best_offer             306
dtype: int64

> `what_customers_said` and `best_offer` Remains the only columns which has `Nan` values

In [23]:
df_dropped["product_id"].duplicated().sum()

np.int64(0)

> It does not contain any duplicates

### Final output csv

In [25]:
df_dropped.to_csv('Cleaned_Ecommerce.csv',index=False,header=True)